using Assimp.Configs;
using CommunityToolkit.Mvvm.ComponentModel;
using CommunityToolkit.Mvvm.Input;
using OpenTK.Mathematics;
using PdfSharpCore.Pdf;
using System.Collections.ObjectModel;
using System.Diagnostics;
using System.IO;
using System.Security.Cryptography;
using System.Windows;
using UnBox3D.Commands;
using UnBox3D.Controls;
using UnBox3D.Controls.States;
using UnBox3D.Rendering.Rulers;
using UnBox3D.Models;
using UnBox3D.Rendering;
using UnBox3D.Rendering.OpenGL;
using UnBox3D.Utils;
using UnBox3D.Views;

using System.Linq;
using System.Threading;
namespace UnBox3D.ViewModels
{
    public partial class MainViewModel : ObservableObject
    {
        #region Fields & Properties

        private readonly ILogger _logger;
        private readonly ISettingsManager _settingsManager;
        private readonly ISceneManager _sceneManager;
        private readonly IGLControlHost _glControlHost;
        private readonly ModelImporter _modelImporter;
        private readonly MouseController _mouseController;
        private readonly ICamera _camera;
        private readonly IFileSystem _fileSystem;
        private readonly BlenderIntegration _blenderIntegration;
        private readonly IBlenderInstaller _blenderInstaller;
        private readonly ModelExporter _modelExporter;
        private readonly ICommandHistory _commandHistory;
        private readonly IRenderer _renderer;
        private readonly IRulerManager       _rulerManager;
        private readonly RulerRenderer       _rulerRenderer;
        private readonly RulerOverlayManager _rulerOverlayManager;
        private string? _importedFilePath; // Global filepath that should be referenced when simplifying
        private List<IAppMesh>? _latestImportedModel; // This is so we can keep track of the original model when playing around with small mesh thresholds.
        private IAppMesh? _lastSelectedMesh; // Keep track of the previously selected mesh so we can remove its highlight
        private Vector3 _normalColor;    // Color used for unselected meshes
        private Vector3 _highlightColor; // Color used for currently selected mesh

        // This property is generated by CommunityToolkit.MVVM and raises change notifications.
        // We react to it in OnSelectedMeshChanged below.
        [ObservableProperty]
        private IAppMesh? selectedMesh;

        [ObservableProperty]
        private bool hierarchyVisible = true;

        [ObservableProperty]
        private float pageWidth = 25.0f;

        [ObservableProperty]
        private float pageHeight = 25.0f;

        [ObservableProperty]
        private float simplificationRatio = 50f; // represents percentage (10–100)

        [ObservableProperty]
        private float smallMeshThreshold = 0f;

        /// <summary>Name of the currently active interaction mode shown in the toolbar.</summary>
        [ObservableProperty]
        private string activeMode = "Select";

        /// <summary>True while a long-running background operation is in progress.</summary>
        [ObservableProperty]
        private bool isBusy = false;

        /// <summary>Short status text shown next to the mesh count in the status bar while busy.</summary>
        [ObservableProperty]
        private string statusMessage = "Ready";

        public ObservableCollection<MeshSummary> Meshes { get; } = new();

        public ICamera Camera => _camera;

        public ObservableCollection<IAppMesh> SceneMeshes => _sceneManager.GetMeshes();

        private MeshSummary? _selectedMeshSummary;
        public MeshSummary? SelectedMeshSummary
        {
            get => _selectedMeshSummary;
            set
            {
                if (_selectedMeshSummary == value) return;

                // unselect old
                if (_selectedMeshSummary != null)
                    _selectedMeshSummary.IsSelected = false;

                _selectedMeshSummary = value;

                // select new
                if (_selectedMeshSummary != null)
                {
                    _selectedMeshSummary.IsSelected = true;
                    SelectedMesh = _selectedMeshSummary.SourceMesh; // keep your existing property updated
                }
                else
                {
                    SelectedMesh = null;
                }

                OnPropertyChanged(nameof(SelectedMeshSummary));
            }
        }
        public IGLControlHost GLControlHost => _glControlHost;
        #endregion

        #region Constructor

        public MainViewModel(ILogger logger, ISettingsManager settingsManager, ISceneManager sceneManager,
            IFileSystem fileSystem, BlenderIntegration blenderIntegration,
            IBlenderInstaller blenderInstaller, ModelExporter modelExporter,
            MouseController mouseController, IGLControlHost glControlHost, ICamera camera, ICommandHistory commandHistory,
            IRenderer renderer, IRulerManager rulerManager, RulerRenderer rulerRenderer,
            RulerOverlayManager rulerOverlayManager)
        {
            _logger = logger;
            _settingsManager = settingsManager;
            _sceneManager = sceneManager;
            _fileSystem = fileSystem;
            _blenderIntegration = blenderIntegration;
            _blenderInstaller = blenderInstaller;
            _modelImporter = new ModelImporter(_settingsManager);
            _modelExporter = modelExporter;
            _mouseController = mouseController;
            _glControlHost = glControlHost;
            _camera = camera;
            _commandHistory = commandHistory;
            _renderer = renderer;
            _rulerManager        = rulerManager;
            _rulerRenderer       = rulerRenderer;
            _rulerOverlayManager = rulerOverlayManager;
            // setup selection highlight colors
            LoadColors();
        }

        #endregion

        #region Model Import Methods

        [RelayCommand]
        private void ImportObjModel()
        {
            var openFileDialog = new Microsoft.Win32.OpenFileDialog
            {
                Filter = "3D Models (*.obj;)|*.obj;"
            };

            // Show the dialog and check if the result is true
            bool? result = openFileDialog.ShowDialog();
            if (result == true)
            {
                string filePath = openFileDialog.FileName;
                _importedFilePath = EnsureImportDirectory(filePath);
                List<IAppMesh> importedMeshes = _modelImporter.ImportModel(_importedFilePath);

                _latestImportedModel = importedMeshes; // Purpose: Remember the model that was imported so that the user can freely mess with something like size thresholds and go back.

                foreach (var mesh in importedMeshes)
                {
                    _sceneManager.AddMesh(mesh);
                    Meshes.Add(new MeshSummary(mesh));
                }

                ToastService.Show($"Imported {importedMeshes.Count} mesh(es)");

                if (_modelImporter.WasScaled)
                {
                    var exportPath = _modelExporter.ExportToObj(_sceneManager.GetMeshes().ToList());
                    if (exportPath != null)
                    {
                        _importedFilePath = exportPath;
                    }

                }
            }
        }

        // Don't call this function directly.
        // Reference _importedFilePath if you want access to the ImportedModels directory.
        private string EnsureImportDirectory(string filePath)
        {
            string importDirectory = _fileSystem.CombinePaths(AppDomain.CurrentDomain.BaseDirectory, "ImportedModels");

            if (!_fileSystem.DoesDirectoryExists(importDirectory))
            {
                _fileSystem.CreateDirectory(importDirectory);
            }

            string destinationPath = _fileSystem.CombinePaths(importDirectory, Path.GetFileName(filePath));
            
            try
            {
                File.Copy(filePath, destinationPath, overwrite: true);
            }
            catch (IOException ex)
            {
                throw new InvalidOperationException("Failed to copy file to ImportedModels directory.", ex);
            }


            return destinationPath;
        }

        public void ImportModelFromPath(string path)
        {
            if (string.IsNullOrWhiteSpace(path) || !File.Exists(path))
                throw new FileNotFoundException("Model file not found.", path);

            var importedMeshes = TryImportWithShadowCopy(path);

            _latestImportedModel = importedMeshes;

            foreach (var mesh in importedMeshes)
            {
                _sceneManager.AddMesh(mesh);
                Meshes.Add(new MeshSummary(mesh));
            }

            _importedFilePath = path;

            if (_modelImporter.WasScaled)
            {
                var exportPath = _modelExporter.ExportToObj(_sceneManager.GetMeshes().ToList());
                if (!string.IsNullOrEmpty(exportPath))
                    _importedFilePath = exportPath;
            }
        }

        private List<IAppMesh> TryImportWithShadowCopy(string sourcePath)
        {
            try
            {
                return _modelImporter.ImportModel(sourcePath);
            }
            catch (IOException ioEx) when (IsSharingViolation(ioEx))
            {
                var tempDir = Path.Combine(Path.GetTempPath(), "UnBox3D", "ShadowCopies");
                Directory.CreateDirectory(tempDir);
                var tempPath = Path.Combine(
                    tempDir, $"{Path.GetFileNameWithoutExtension(sourcePath)}_{Guid.NewGuid():N}{Path.GetExtension(sourcePath)}");

                SafeCopyWithRetry(sourcePath, tempPath, attempts: 10, delayMs: 80);
                try
                {
                    return _modelImporter.ImportModel(tempPath);
                }
                finally
                {
                    try { File.Delete(tempPath); } catch { /* best-effort cleanup */ }
                }
            }
        }

        private static bool IsSharingViolation(IOException ex) =>
            (ex.HResult & 0xFFFF) == 32           // ERROR_SHARING_VIOLATION
         || (ex.HResult & 0xFFFF) == 33           // ERROR_LOCK_VIOLATION
         || ex.Message.IndexOf("being used by another process", StringComparison.OrdinalIgnoreCase) >= 0;

        private static void SafeCopyWithRetry(string src, string dst, int attempts, int delayMs)
        {
            for (int i = 0; i < attempts; i++)
            {
                try
                {
                    using var s = new FileStream(src, FileMode.Open, FileAccess.Read, FileShare.ReadWrite);
                    using var d = new FileStream(dst, FileMode.Create, FileAccess.Write, FileShare.Read);
                    s.CopyTo(d);
                    return;
                }
                catch (IOException) when (i < attempts - 1)
                {
                    Thread.Sleep(delayMs * (i + 1));
                }
            }

            using var sFinal = new FileStream(src, FileMode.Open, FileAccess.Read, FileShare.ReadWrite);
            using var dFinal = new FileStream(dst, FileMode.Create, FileAccess.Write, FileShare.Read);
            sFinal.CopyTo(dFinal);
        }


        #endregion

        #region Unfolding Process Methods

        private async Task ProcessUnfolding(string inputModelPath)
        {
            Debug.WriteLine("Input model is coming from: " + inputModelPath);

            var installWindow = new LoadingWindow
            {
                StatusHint = "Installing Blender...",
                Owner = System.Windows.Application.Current.MainWindow,
                IsProgressIndeterminate = false
            };
            installWindow.Show();

            var installProgress = new Progress<double>(value =>
            {
                installWindow.UpdateProgress(value * 100);
                installWindow.UpdateStatus($"Installing Blender... {Math.Round(value * 100)}%");
            });

            await _blenderInstaller.CheckAndInstallBlender(installProgress);
            installWindow.Close();

            if (!_blenderInstaller.IsBlenderInstalled())
            {
                await ShowWpfMessageBoxAsync(
                    "Blender is required to unfold models but was not found. Please install Blender before proceeding.",
                    "Missing Dependency", MessageBoxButton.OK, MessageBoxImage.Warning);
                return;
            }
            else
            {
                var loadingWindow = new LoadingWindow
                {
                    StatusHint = "This may take several minutes depending on model complexity",
                    Owner = System.Windows.Application.Current.MainWindow,
                    IsProgressIndeterminate = false
                };
                loadingWindow.Show();

                if (_fileSystem == null || _blenderIntegration == null)
                {
                    loadingWindow.Close();
                    await ShowWpfMessageBoxAsync("Internal error: dependencies not initialized.", "Error", MessageBoxButton.OK, MessageBoxImage.Error);
                    return;
                }

                if (PageWidth == 0 || PageHeight == 0)
                {
                    loadingWindow.Close();
                    await ShowWpfMessageBoxAsync("Page Dimensions cannot be 0.", "Error", MessageBoxButton.OK, MessageBoxImage.Error);
                    return;
                }

                using SaveFileDialog saveFileDialog = new()
                {
                    Title = "Save your unfolded file",
                    Filter = "SVG Files|*.svg|PDF Files|*.pdf",
                    FileName = "MyUnfoldedFile"
                };

                if (saveFileDialog.ShowDialog() != DialogResult.OK)
                {
                    loadingWindow.Close();
                    return;
                }

                string filePath = saveFileDialog.FileName;
                string ext = Path.GetExtension(filePath).ToLowerInvariant();
                string? userSelectedPath = Path.GetDirectoryName(filePath);

                if (string.IsNullOrEmpty(userSelectedPath))
                {
                    loadingWindow.Close();
                    await ShowWpfMessageBoxAsync("Unable to determine the selected directory.", "Error", MessageBoxButton.OK, MessageBoxImage.Error);
                    return;
                }

                string newFileName = Path.GetFileNameWithoutExtension(filePath);
                string format = ext == ".pdf" ? "PDF" : "SVG";

                string baseDir = AppDomain.CurrentDomain.BaseDirectory;
                string outputDirectory = _fileSystem.CombinePaths(baseDir, "UnfoldedOutputs");
                string scriptPath = _fileSystem.CombinePaths(baseDir, "Scripts", "unfolding_script.py");

                if (!_fileSystem.DoesDirectoryExists(outputDirectory))
                {
                    _fileSystem.CreateDirectory(outputDirectory);
                }

                CleanupUnfoldedFolder(outputDirectory);

                double incrementWidth = PageWidth;
                double incrementHeight = PageHeight;
                bool success = false;
                string errorMessage = "";
                int iteration = 0;

                loadingWindow.UpdateStatus("Preparing Blender environment...");
                await DispatcherHelper.DoEvents();

                while (!success)
                {
                    iteration++;
                    loadingWindow.UpdateStatus($"Processing with Blender (Attempt {iteration})...");
                    loadingWindow.UpdateProgress((double)iteration / 100 * 50);
                    await DispatcherHelper.DoEvents();

                    success = await Task.Run(() => _blenderIntegration.RunBlenderScript(
                        inputModelPath, outputDirectory, scriptPath,
                        newFileName, incrementWidth, incrementHeight, "SVG", out errorMessage));

                    if (!success)
                    {
                        if (errorMessage.Contains("continue"))
                        {
                            incrementWidth++;
                            incrementHeight++;
                            loadingWindow.UpdateStatus($"Retrying with new dimensions: {incrementWidth} x {incrementHeight}");
                            await DispatcherHelper.DoEvents();
                        }
                        else
                        {
                            loadingWindow.Close();

                            await loadingWindow.Dispatcher.InvokeAsync(() =>
                            {
                                System.Windows.Application.Current.MainWindow?.Activate();
                                System.Windows.MessageBox.Show(
                                    errorMessage,
                                    "Error Processing File",
                                    MessageBoxButton.OK,
                                    MessageBoxImage.Error,
                                    MessageBoxResult.OK,
                                    System.Windows.MessageBoxOptions.DefaultDesktopOnly);
                            });

                            return;
                        }
                    }
                }

                loadingWindow.UpdateStatus("Processing unfolded panels...");
                await DispatcherHelper.DoEvents();

                string[] svgPanelFiles = Directory.GetFiles(outputDirectory, "*.svg");
                int totalPanels = svgPanelFiles.Length;

                for (int i = 0; i < totalPanels; i++)
                {
                    string svgFile = svgPanelFiles[i];
                    loadingWindow.UpdateStatus($"Processing panel {i + 1} of {totalPanels}");
                    loadingWindow.UpdateProgress(50 + ((double)i / totalPanels * 30));
                    await DispatcherHelper.DoEvents();

                    await Task.Run(() => SVGEditor.ExportSvgPanels(svgFile, outputDirectory, newFileName, i,
                        PageWidth * 1000f, PageHeight * 1000f));
                }

                loadingWindow.UpdateStatus("Exporting final files...");
                loadingWindow.UpdateProgress(80);
                await DispatcherHelper.DoEvents();

                if (format == "SVG")
                {
                    string[] svgFiles = Directory.GetFiles(outputDirectory, $"{newFileName}*.svg");
                    int fileCount = svgFiles.Length;

                    for (int i = 0; i < fileCount; i++)
                    {
                        string source = svgFiles[i];
                        string suffix = source.Substring(source.IndexOf(newFileName) + newFileName.Length);
                        string destination = Path.Combine(userSelectedPath, newFileName + suffix);

                        loadingWindow.UpdateStatus($"Exporting file {i + 1} of {fileCount}");
                        loadingWindow.UpdateProgress(80 + ((double)i / fileCount * 20));
                        await DispatcherHelper.DoEvents();

                        File.Move(source, destination, overwrite: true); // Optionally wrap in _fileSystem
                    }
                }
                else if (format == "PDF")
                {
                    string pdfFile = Path.Combine(outputDirectory, $"{newFileName}.pdf");

                    string[] svgFiles = Directory.GetFiles(outputDirectory, $"{newFileName}_panel_page*.svg");
                    int fileCount = svgFiles.Length;

                    var pdf = new PdfDocument();
                    bool allSuccessful = true;

                    for (int i = 0; i < fileCount; i++)
                    {
                        string svgFile = svgFiles[i];
                        loadingWindow.UpdateStatus($"Combining file {i + 1} of {fileCount} into PDF...");
                        loadingWindow.UpdateProgress(80 + ((double)i / fileCount * 20));
                        await DispatcherHelper.DoEvents();

                        bool successful = await Task.Run(() => SVGEditor.ExportToPdf(svgFile, pdf));
                        if (!successful)
                        {
                            allSuccessful = false;
                            break;
                        }
                    }

                    if (allSuccessful)
                    {
                        pdf.Save(pdfFile);
                        string destination = Path.Combine(userSelectedPath, $"{newFileName}.pdf");
                        File.Move(pdfFile, destination, overwrite: true);
                    }
                    else
                    {
                        await ShowWpfMessageBoxAsync($"The SVG files are too large to be combined into partitioned panels for PDF. Will instead use the fallback PDF which may result in loss of some panels. Exporting will continue.", "Unable to allocate the required memory", MessageBoxButton.OK, MessageBoxImage.Warning);

                        Debug.WriteLine($"incrW: {incrementWidth} incrH: {incrementHeight}");

                        await Task.Run(() => _blenderIntegration.RunBlenderScript(
                            inputModelPath, outputDirectory, scriptPath,
                            newFileName, incrementWidth, incrementHeight, "PDF", out errorMessage));

                        string destination = Path.Combine(userSelectedPath, $"{newFileName}.pdf");
                        File.Move(pdfFile, destination, overwrite: true);
                    }
                }
                loadingWindow.UpdateStatus("Cleaning up temporary files...");
                loadingWindow.UpdateProgress(100);
                await DispatcherHelper.DoEvents();
                CleanupUnfoldedFolder(outputDirectory);

                loadingWindow.Close();

                await ShowWpfMessageBoxAsync($"{format} file has been exported successfully!",
                    "Export Complete", MessageBoxButton.OK, MessageBoxImage.Information);
            }
        }

        [RelayCommand]
        private async Task UnfoldMesh(IAppMesh mesh)
        {
            if (mesh == null)
                return;

            // 1. Export the single mesh to a temporary .obj file
            string fileName = $"unfold_temp_{Guid.NewGuid()}.obj";
            string? exportedPath = _modelExporter.ExportToObj(new List<IAppMesh> { mesh }, fileName);

            if (string.IsNullOrWhiteSpace(exportedPath))
            {
                await ShowWpfMessageBoxAsync("Failed to export mesh for unfolding.", "Export Error",
                                             MessageBoxButton.OK, MessageBoxImage.Error);
                return;
            }

            // 2. Unfold just this mesh using the same logic you already have
            await ProcessUnfolding(exportedPath);
        }


        private void CleanupUnfoldedFolder(string folderPath)
        {
            try
            {
                string[] files = Directory.GetFiles(folderPath);
                foreach (string file in files)
                {
                    File.Delete(file);
                }
            }
            catch (Exception ex)
            {
                // Synchronously show an error if cleanup fails.
                System.Windows.Application.Current.Dispatcher.Invoke(() =>
                {
                    System.Windows.Application.Current.MainWindow.Activate();
                    System.Windows.MessageBox.Show(
                        $"An error occurred during cleanup: {ex.Message}",
                        "Cleanup Error",
                        MessageBoxButton.OK,
                        MessageBoxImage.Error,
                        MessageBoxResult.OK,
                        System.Windows.MessageBoxOptions.DefaultDesktopOnly);
                });
            }
        }

        #endregion

        #region Relay Commands

        [RelayCommand]
        private async Task ExportUnfoldModel()
        {
            if (string.IsNullOrEmpty(_importedFilePath))
            {
                await ShowWpfMessageBoxAsync("No model imported to unfold.", "Error", MessageBoxButton.OK, MessageBoxImage.Error);
                return;
            }
            await ProcessUnfolding(_importedFilePath);
        }

        [RelayCommand]
        private void ResetView()
        {
            ToastService.Show("View reset.", isError: false);
        }

        [RelayCommand]
        private void ToggleHierarchy()
        {
            HierarchyVisible = !HierarchyVisible;
        }

        [RelayCommand]
        private static async Task About()
        {
            await ShowWpfMessageBoxAsync("UnBox3D - A 3D Model Viewer", "About", MessageBoxButton.OK, MessageBoxImage.Information);
        }

        [RelayCommand]
        private async Task ExportMesh(IAppMesh mesh)
        {
            if (mesh == null)
                return;

            var path = PromptForSaveLocation();
            if (string.IsNullOrWhiteSpace(path))
                return;

            var exported = _modelExporter.ExportToObjAbsolutePath(new List<IAppMesh> { mesh }, path);
            if (exported != null)
            {
                await ShowWpfMessageBoxAsync($"Exported mesh to: {exported}",
                                             "Export Mesh",
                                             MessageBoxButton.OK,
                                             MessageBoxImage.Information);
            }
            else
            {
                await ShowWpfMessageBoxAsync("Failed to export mesh.",
                                             "Export Mesh",
                                             MessageBoxButton.OK,
                                             MessageBoxImage.Error);
            }
        }

        [RelayCommand]
        private async Task ClearScene()
        {
            bool confirmed = await System.Windows.Application.Current.Dispatcher.InvokeAsync(() =>
            {
                var dlg = new UnBox3D.Views.ConfirmDialog(
                    title:         "Clear Scene",
                    message:       "This will remove all meshes from the scene. This action cannot be undone.",
                    confirmLabel:  "Clear",
                    cancelLabel:   "Cancel");
                dlg.Owner = System.Windows.Application.Current.MainWindow;
                dlg.ShowDialog();
                return dlg.Confirmed;
            });

            if (confirmed)
            {
                _sceneManager.ClearScene();
                Meshes.Clear();
            }
        }

        // Internal helper used by Replace* operations — does NOT push to history.
        private void DeleteMeshInternal(IAppMesh mesh)
        {
            if (mesh == null) return;

            _sceneManager.DeleteMesh(mesh);
            _latestImportedModel?.Remove(mesh);

            if (mesh is IDisposable disposableMesh)
                disposableMesh.Dispose();

            var summaryToRemove = Meshes.FirstOrDefault(ms => ms.SourceMesh == mesh);
            if (summaryToRemove != null)
                Meshes.Remove(summaryToRemove);
        }

        // Called by the Delete button in the mesh hierarchy panel.
        // Routes through CommandHistory so Ctrl+Z / Redo work correctly.
        [RelayCommand]
        private void DeleteMesh(IAppMesh mesh)
        {
            if (mesh == null) return;

            var cmd = new DeleteCommand(_glControlHost, _sceneManager, mesh);
            _commandHistory.PushCommand(cmd);
            cmd.Execute();

            // Keep the UI hierarchy in sync immediately.
            _latestImportedModel?.Remove(mesh);
            var summaryToRemove = Meshes.FirstOrDefault(ms => ms.SourceMesh == mesh);
            if (summaryToRemove != null)
                Meshes.Remove(summaryToRemove);
        }


        [RelayCommand]
        private async Task ExportModel()
        {
            // 1. Prompt user for the export path
            string? path = PromptForSaveLocation();
            if (string.IsNullOrEmpty(path))
                return; // user cancelled

            // 2. Export all meshes
            var meshesToExport = _sceneManager.GetMeshes().ToList();
            var savedPath = _modelExporter.ExportToObjAbsolutePath(meshesToExport, path);

            // 3. Notify user of success/failure
            if (savedPath != null)
            {
                await ShowWpfMessageBoxAsync($"Exported all meshes to: {savedPath}",
                                             "Export Meshes",
                                             MessageBoxButton.OK,
                                             MessageBoxImage.Information);
            }
            else
            {
                await ShowWpfMessageBoxAsync("Failed to export meshes.",
                                             "Export Meshes",
                                             MessageBoxButton.OK,
                                             MessageBoxImage.Error);
            }
        }

        #endregion

        #region Mesh Simplification Commands

        [RelayCommand]
        private async Task ReplaceSceneWithBoundingBoxes()
        {
            // Value set from UI slider
            float threshold = SmallMeshThreshold;

            // 1. Generate bounding boxes and load them
            List<AppMesh> boxMeshList = _sceneManager.LoadBoundingBoxes();

            // 2. Clear the scene and UI
            _sceneManager.ClearScene();
            Meshes.Clear();

            // 3. Export the generated bounding boxes to a temp .obj file
            string tempFileName = $"bounding_boxes_scene_{Guid.NewGuid()}.obj";
            string? exportedPath = _modelExporter.ExportToObj(boxMeshList.Cast<IAppMesh>().ToList(), tempFileName);

            if (string.IsNullOrWhiteSpace(exportedPath))
            {
                await ShowWpfMessageBoxAsync("Failed to export bounding boxes.", "Export Error",
                                             MessageBoxButton.OK, MessageBoxImage.Error);
                return;
            }

            // 4. Re-import the exported .obj file to fully reload it into the scene
            var importedMeshes = _modelImporter.ImportModel(exportedPath);
            _importedFilePath = exportedPath;
            foreach (var mesh in importedMeshes)
            {
                _sceneManager.AddMesh(mesh);
                Meshes.Add(new MeshSummary(mesh));
            }
            await Task.CompletedTask;
        }

        [RelayCommand]
        private async Task ReplaceWithCylinderOption(IAppMesh mesh)
        {
            if (mesh == null) return;

            Vector3 center = _sceneManager.GetMeshCenter(mesh.GetG4Mesh());
            Vector3 meshDimensions = _sceneManager.GetMeshDimensions(mesh.GetG4Mesh());

            bool isXAligned = (meshDimensions.X < meshDimensions.Z);
            float radius = Math.Max(Math.Min(meshDimensions.X, meshDimensions.Z), meshDimensions.Y) / 2;
            float height = isXAligned ? meshDimensions.X : meshDimensions.Z;

            string name;
            if (mesh.Name.Contains("(Cylinder)"))      name = mesh.Name;
            else if (mesh.Name.Contains("(Prism)"))    name = mesh.Name.Replace("(Prism)",  "(Cylinder)");
            else if (mesh.Name.Contains("(Wedge)"))    name = mesh.Name.Replace("(Wedge)",  "(Cylinder)");
            else                                       name = mesh.Name + " (Cylinder)";

            AppMesh cylinder = GeometryGenerator.CreateRotatedCylinder(center, radius, height, 32, Vector3.UnitX, name);

            var cmd = new ReplaceMeshCommand(_sceneManager, _glControlHost, mesh, cylinder);
            _commandHistory.PushCommand(cmd);
            cmd.Execute();

            _latestImportedModel?.Remove(mesh);
            var oldSummary = Meshes.FirstOrDefault(ms => ms.SourceMesh == mesh);
            if (oldSummary != null) Meshes.Remove(oldSummary);
            Meshes.Add(new MeshSummary(cylinder));

            await Task.CompletedTask;
        }

        // If you want to implement replace with cylinder by clicking
        [RelayCommand]
        private void ReplaceWithCylinderClick()
        {
            if (SelectedMesh != null)
                ReplaceWithCylinderOption(SelectedMesh);
            else
                ToastService.Show("Select a mesh first.", isError: false);
        }

        

        [RelayCommand]
        private async void ReplaceWithCubeOption(IAppMesh mesh)
        {
            if (mesh == null) return;

            Vector3 center = _sceneManager.GetMeshCenter(mesh.GetG4Mesh());
            Vector3 meshDimensions = _sceneManager.GetSmallestMeshDimensions(mesh.GetG4Mesh());

            string name;
            if (mesh.Name.Contains("(Prism)"))         name = mesh.Name;
            else if (mesh.Name.Contains("(Cylinder)")) name = mesh.Name.Replace("(Cylinder)", "(Prism)");
            else if (mesh.Name.Contains("(Wedge)"))    name = mesh.Name.Replace("(Wedge)",    "(Prism)");
            else                                       name = mesh.Name + " (Prism)";

            AppMesh cube = GeometryGenerator.CreateBox(center, meshDimensions.X, meshDimensions.Y, meshDimensions.Z, name);

            var cmd = new ReplaceMeshCommand(_sceneManager, _glControlHost, mesh, cube);
            _commandHistory.PushCommand(cmd);
            cmd.Execute();

            _latestImportedModel?.Remove(mesh);
            var oldSummary = Meshes.FirstOrDefault(ms => ms.SourceMesh == mesh);
            if (oldSummary != null) Meshes.Remove(oldSummary);
            Meshes.Add(new MeshSummary(cube));
        }

        [RelayCommand]
        private void ReplaceWithCubeClick()
        {
            if (SelectedMesh != null)
                ReplaceWithCubeOption(SelectedMesh);
            else
                ToastService.Show("Select a mesh first.", isError: false);
        }

        [RelayCommand]
        private async void ReplaceWithWedgeOption(IAppMesh mesh)
        {
            if (mesh == null) return;

            Vector3 center = _sceneManager.GetMeshCenter(mesh.GetG4Mesh());
            Vector3 meshDimensions = _sceneManager.GetSmallestMeshDimensions(mesh.GetG4Mesh());

            string name;
            if (mesh.Name.Contains("(Wedge)"))         name = mesh.Name;
            else if (mesh.Name.Contains("(Cylinder)")) name = mesh.Name.Replace("(Cylinder)", "(Wedge)");
            else if (mesh.Name.Contains("(Prism)"))    name = mesh.Name.Replace("(Prism)",    "(Wedge)");
            else                                       name = mesh.Name + " (Wedge)";

            AppMesh wedge = GeometryGenerator.CreateWedge(center, meshDimensions.X, meshDimensions.Y, meshDimensions.Z, name);

            var cmd = new ReplaceMeshCommand(_sceneManager, _glControlHost, mesh, wedge);
            _commandHistory.PushCommand(cmd);
            cmd.Execute();

            _latestImportedModel?.Remove(mesh);
            var oldSummary = Meshes.FirstOrDefault(ms => ms.SourceMesh == mesh);
            if (oldSummary != null) Meshes.Remove(oldSummary);
            Meshes.Add(new MeshSummary(wedge));
        }

        [RelayCommand]
        private void ReplaceWithWedgeClick()
        {
            if (SelectedMesh != null)
                ReplaceWithWedgeOption(SelectedMesh);
            else
                ToastService.Show("Select a mesh first.", isError: false);
        }

        [RelayCommand]
        private async Task SimplifyQEC(IAppMesh mesh)
        {
            await RunPythonSimplificationSingle(mesh, "quadric_edge_collapse");
        }

        [RelayCommand]
        private async Task SimplifyFQD(IAppMesh mesh)
        {
            await RunPythonSimplificationSingle(mesh, "fast_quadric_decimation");
        }

        [RelayCommand]
        private async Task SimplifyVC(IAppMesh mesh)
        {
            await RunPythonSimplificationSingle(mesh, "vertex_clustering");
        }

        [RelayCommand]
        private async Task SimplifyAllQEC()
        {
            await RunPythonSceneSimplification("quadric_edge_collapse");
        }

        [RelayCommand]
        private async Task SimplifyAllFQD()
        {
            await RunPythonSceneSimplification("fast_quadric_decimation");
        }

        [RelayCommand]
        private async Task SimplifyAllVC()
        {
            await RunPythonSceneSimplification("vertex_clustering");
        }

        private async Task RunPythonSceneSimplification(string method)
        {
            if (Meshes.ToList().Count == 0)
            {
                await ShowWpfMessageBoxAsync("No meshes to simplify.", "Warning", MessageBoxButton.OK, MessageBoxImage.Warning);
                return;
            }

            IsBusy = true;
            StatusMessage = "Simplifying scene...";

            var loadingWindow = new LoadingWindow
            {
                StatusHint = $"Simplifying all meshes… This may take a few moments.",
                Owner = System.Windows.Application.Current.MainWindow,
                IsProgressIndeterminate = true
            };
            loadingWindow.Show();

            if (method == "quadric_edge_collapse")
                loadingWindow.UpdateStatus($"Quadric Edge Collapse Simplification");
            else if (method == "fast_quadric_decimation")
                loadingWindow.UpdateStatus($"Fast Quadric Decimation");
            else if (method == "vertex_clustering")
                loadingWindow.UpdateStatus($"Vertex Clustering Simplification");

            try
            {
                // 1. Export all current meshes to a temp OBJ
                string? exportFile = _modelExporter.ExportToObj(Meshes.Select(m => m.SourceMesh).ToList(), $"scene_to_simplify.obj");
                if (exportFile == null)
                {
                    await ShowWpfMessageBoxAsync("Failed to export current scene.", "Error", MessageBoxButton.OK, MessageBoxImage.Error);
                    return;
                }

                // 2. Prepare paths and arguments
                string simplifiedOutput = Path.Combine(Path.GetTempPath(), $"simplified_scene_{method}.obj");
                string exePath = Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "Scripts", "simplify.exe");
                float ratio = Math.Clamp(SimplificationRatio, 10, 100) / 100f;

                var startInfo = new ProcessStartInfo
                {
                    FileName = exePath,
                    Arguments = $"\"{exportFile}\" \"{simplifiedOutput}\" \"{method}\" \"{ratio}\"",
                    RedirectStandardOutput = true,
                    RedirectStandardError = true,
                    UseShellExecute = false,
                    CreateNoWindow = true
                };

                using var process = new Process { StartInfo = startInfo };
                process.Start();
                string stdout = await process.StandardOutput.ReadToEndAsync();
                string stderr = await process.StandardError.ReadToEndAsync();
                await process.WaitForExitAsync();

                if (process.ExitCode != 0)
                {
                    await ShowWpfMessageBoxAsync($"simplify.exe error:\n{stderr}", "Simplification Failed", MessageBoxButton.OK, MessageBoxImage.Error);
                    return;
                }

                // 3. Import simplified mesh
                loadingWindow.UpdateStatus("Importing simplified mesh...");
                var simplifiedMeshes = _modelImporter.ImportModel(simplifiedOutput);
                if (simplifiedMeshes.Count == 0)
                {
                    await ShowWpfMessageBoxAsync("No mesh found in simplified result.", "Warning", MessageBoxButton.OK, MessageBoxImage.Warning);
                    return;
                }

                // 4. Clear current scene and replace with new simplified mesh
                _sceneManager.ClearScene();
                Meshes.Clear();
                foreach (var simplified in simplifiedMeshes)
                {
                    _sceneManager.AddMesh(simplified);
                    Meshes.Add(new MeshSummary(simplified));
                }
            }
            catch (Exception ex)
            {
                await ShowWpfMessageBoxAsync($"Exception: {ex.Message}", "Error", MessageBoxButton.OK, MessageBoxImage.Error);
            }
            finally
            {
                loadingWindow.Close();
                IsBusy = false;
                StatusMessage = "Ready";
            }
        }

        private async Task RunPythonSimplificationSingle(IAppMesh mesh, string method)
        {
            // 1. Export just this single mesh to a temp file
            string tempName = $"temp_singlemesh_{Guid.NewGuid()}.obj";
            var tempFile = _modelExporter.ExportToObj(new List<IAppMesh> { mesh }, tempName);

            if (tempFile == null)
            {
                await ShowWpfMessageBoxAsync("Failed to export single mesh.", "Error",
                                             MessageBoxButton.OK, MessageBoxImage.Error);
                return;
            }

            // 2. Prepare the output from the simplify.exe
            string baseOutput = Path.Combine(Path.GetTempPath(), $"simplified_{method}.obj");

            IsBusy = true;
            StatusMessage = "Simplifying mesh...";

            // 3. Show a loading window
            var loadingWindow = new LoadingWindow
            {
                StatusHint = $"Simplifying mesh… This may take a while.",
                Owner = System.Windows.Application.Current.MainWindow,
                IsProgressIndeterminate = true
            };
            loadingWindow.Show();

            if (method == "quadric_edge_collapse")
                loadingWindow.UpdateStatus($"Quadric Edge Collapse Simplification");
            else if (method == "fast_quadric_decimation")
                loadingWindow.UpdateStatus($"Fast Quadric Decimation");
            else if (method == "vertex_clustering")
                loadingWindow.UpdateStatus($"Vertex Clustering Simplification");

            try
            {
                var exePath = Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "Scripts", "simplify.exe");

                float ratio = Math.Clamp(SimplificationRatio, 10, 100) / 100f;

                var startInfo = new ProcessStartInfo
                {
                    FileName = exePath,
                    Arguments = $"\"{tempFile}\" \"{baseOutput}\" \"{method}\" \"{ratio}\"",
                    RedirectStandardOutput = true,
                    RedirectStandardError = true,
                    UseShellExecute = false,
                    CreateNoWindow = true
                };

                using var process = new Process { StartInfo = startInfo };
                process.Start();

                string stdout = await process.StandardOutput.ReadToEndAsync();
                string stderr = await process.StandardError.ReadToEndAsync();
                await process.WaitForExitAsync();

                if (process.ExitCode != 0)
                {
                    await ShowWpfMessageBoxAsync($"simplify.exe error:\n{stderr}",
                                                 "Simplification Failed",
                                                 MessageBoxButton.OK, MessageBoxImage.Error);
                    return;
                }

                // 5. Re-import the simplified file
                var simplifiedMeshes = _modelImporter.ImportModel(baseOutput);
                if (simplifiedMeshes.Count > 0)
                {
                    var simplified = simplifiedMeshes[0];
                    _sceneManager.ReplaceMesh(mesh, simplified);

                    // 6. Update UI
                    var oldSummary = Meshes.FirstOrDefault(ms => ms.SourceMesh == mesh);
                    if (oldSummary != null)
                    {
                        Meshes.Remove(oldSummary);
                        Meshes.Add(new MeshSummary(simplified));
                    }
                }
            }
            catch (Exception ex)
            {
                await ShowWpfMessageBoxAsync($"Exception: {ex.Message}",
                                             "Error",
                                             MessageBoxButton.OK,
                                             MessageBoxImage.Error);
            }
            finally
            {
                loadingWindow.Close();
                IsBusy = false;
                StatusMessage = "Ready";
            }
        }

        #endregion

        #region Helper Methods

        /// <summary>
        /// Shows a WPF MessageBox asynchronously using the UI Dispatcher.
        /// </summary>
        private static async Task<MessageBoxResult> ShowWpfMessageBoxAsync(string message, string title, MessageBoxButton button, MessageBoxImage image)
        {
            return await System.Windows.Application.Current.Dispatcher.InvokeAsync(() =>
            {
                // Activate main window so the MessageBox appears on top.
                System.Windows.Application.Current.MainWindow.Activate();
                return System.Windows.MessageBox.Show(
                    message,
                    title,
                    button,
                    image,
                    MessageBoxResult.OK,
                    System.Windows.MessageBoxOptions.DefaultDesktopOnly);
            });
        }

        private string? PromptForSaveLocation()
        {
            var dialog = new Microsoft.Win32.SaveFileDialog
            {
                Title = "Save Mesh As .obj",
                Filter = "Wavefront OBJ (*.obj)|*.obj",
                FileName = "export.obj"
            };

            // If user clicks 'Save'
            bool? result = dialog.ShowDialog();
            if (result == true)
            {
                return dialog.FileName;
            }
            return null;
        }

        // This method is auto-discovered by the MVVM source generator because its name matches
        // the property: On{PropertyName}Changed. It runs every time SelectedMesh actually changes.
        partial void OnSelectedMeshChanged(IAppMesh? value)
        {
            // 1) If there was a previously highlighted mesh, restore it to the normal color.
            if (_lastSelectedMesh != null)
                _lastSelectedMesh.SetColor(_normalColor);

            // 2) If we have a new selection, apply the highlight color.
            if (value != null)
                value.SetColor(_highlightColor);

            // 3) Remember the current selection so we can un-highlight it next time.
            _lastSelectedMesh = value;

            // 4) Retarget the gizmo when the selection changes while a transform mode is active.
            //    This ensures panel-driven selection updates the gizmo just like a viewport click.
            RetargetGizmoToSelectedMesh();

            // 5) Ask the GL view to repaint so the color change shows immediately.
            _glControlHost.Render();
        }

        /// <summary>
        /// True while Move, Rotate, or Gimbal mode is the active mouse state.
        /// Used by the MainWindow viewport click handler to avoid updating SelectedMesh
        /// while the state machine owns mesh interaction.
        /// </summary>
        public bool IsTransformModeActive =>
            _mouseController.GetState() is MoveState or RotateState or GimbalState or RulerState;

        /// <summary>
        /// Points the active gizmo at the currently selected mesh, or hides it when nothing is selected.
        /// Must be called any time the selected mesh or its world position changes (selection change, undo, redo).
        /// </summary>
        private void RetargetGizmoToSelectedMesh()
        {
            if (SelectedMesh != null)
            {
                switch (_mouseController.GetState())
                {
                    case GimbalState gs: gs.SetSelectedMesh(SelectedMesh); break;
                    case MoveState ms:   ms.SetSelectedMesh(SelectedMesh); break;
                    case RotateState rs: rs.SetSelectedMesh(SelectedMesh); break;
                }
            }
            else
            {
                _renderer.SetActiveGizmoMesh(null);
            }
        }

        /// <summary>
        /// Loads the mesh colors from settings into <c>normalColor</c> and <c>highlightColor</c>.
        /// Falls back to sensible defaults when a setting is missing or unrecognized.
        /// Call once from the constructor.
        /// </summary>
        private void LoadColors()
        {
            var rs = new RenderingSettings();

            _normalColor = ReadColorOrDefault(
                sectionKey: rs.GetKey(),
                settingName: RenderingSettings.MeshColor,
                fallback: Colors.Red,
                labelForLogs: "Mesh color"
            );

            _highlightColor = ReadColorOrDefault(
                sectionKey: rs.GetKey(),
                settingName: RenderingSettings.MeshHighlightColor,
                fallback: Colors.Blue,
                labelForLogs: "Mesh highlight color"
            );
        }
        /// <summary>
        /// Reads a color string from settings, tries to parse it via <see cref="TryParseColor"/>,
        /// and returns a fallback when parsing fails. Logs a warning when a non-empty value is unrecognized.
        /// </summary>
        /// <param name="sectionKey">Settings section key (e.g., from <see cref="RenderingSettings.GetKey"/>).</param>
        /// <param name="settingName">Concrete setting name (e.g., <see cref="RenderingSettings.MeshColor"/>).</param>
        /// <param name="fallback">Color used when value is missing or invalid.</param>
        /// <param name="labelForLogs">Human-readable label used in warnings.</param>
        /// <returns><see cref="Vector3"/> - The parsed color or the provided fallback.</returns>
        private Vector3 ReadColorOrDefault(string sectionKey, string settingName, Vector3 fallback, string labelForLogs)
        {
            // Fetch raw string (may be null/empty, localized, or user-entered)
            string? raw = _settingsManager.GetSetting<string>(sectionKey, settingName);

            // Parsed successfully
            if (TryParseColor(raw, out var parsedColor))
                return parsedColor;

            if (!string.IsNullOrWhiteSpace(raw))
                Debug.WriteLine($"Warning: {labelForLogs} '{raw}' not recognized. Using fallback.");

            return fallback;
        }
        /// <summary>
        /// Attempts to parse a color name into an RGB <see cref="Vector3"/> using the app's color map.
        /// Normalizes input (trim/lower/remove spaces) so values like "Light Blue" and "lightblue" match.
        /// </summary>
        /// <param name="raw">Raw color string from settings (may be null/empty).</param>
        /// <param name="color">Parsed color when the method returns <see langword="true"/>.</param>
        /// <returns><see langword="true"/> if parsing succeeded; otherwise <see langword="false"/>.</returns>
        /// <remarks>
        /// Future extension points:
        /// - Add hex support (e.g., #RRGGBB) or "r,g,b" numeric parsing.
        /// </remarks>
        private static bool TryParseColor(string? raw, out Vector3 color)
        {
            color = default;

            if (string.IsNullOrWhiteSpace(raw))
                return false;

            // Normalize: "Light Blue" -> "lightblue"
            string key = raw.Trim().ToLowerInvariant().Replace(" ", "");

            // use your existing map
            if (Colors.colorMap.TryGetValue(key, out color))
                return true;

            // (Optional) add hex support later, e.g. #RRGGBB -> Vector3
            // if (TryParseHex(key, out color)) return true;

            return false;
        }


        #endregion

        [RelayCommand]
        private void Exit()
        {
            System.Windows.Application.Current.Shutdown();
        }

        #region Undo / Redo

        [RelayCommand(CanExecute = nameof(CanUndoAction))]
        private void UndoAction()
        {
            var cmd = _commandHistory.PopCommand();
            if (cmd == null) return;
            cmd.Undo();
            _commandHistory.PushRedoCommand(cmd);
            RefreshMeshesCollection();
            RetargetGizmoToSelectedMesh();
            _glControlHost.Render();
        }
        private bool CanUndoAction() => _commandHistory.CanUndo;

        [RelayCommand(CanExecute = nameof(CanRedoAction))]
        private void RedoAction()
        {
            var cmd = _commandHistory.PopRedoCommand();
            if (cmd == null) return;
            cmd.Execute();
            _commandHistory.PushCommand(cmd);
            RefreshMeshesCollection();
            RetargetGizmoToSelectedMesh();
            _glControlHost.Render();
        }
        private bool CanRedoAction() => _commandHistory.CanRedo;

        // Re-evaluate CanExecute every time the history stacks change.
        public void Initialize(IGLControlHost controlHost, ILogger logger, IBlenderInstaller blenderInstaller)
        {
            _commandHistory.HistoryChanged += (_, __) =>
            {
                UndoActionCommand.NotifyCanExecuteChanged();
                RedoActionCommand.NotifyCanExecuteChanged();
            };
        }

        #endregion

        #region Mode-Switching Commands

        [RelayCommand]
        private void SetSelectMode()
        {
            ActiveMode = "Select";
            _renderer.SetActiveGizmoMesh(null);
            var state = new DefaultState(_sceneManager, _glControlHost, _camera, new RayCaster(_glControlHost, _camera));
            _mouseController.SetState(state);
        }

        [RelayCommand]
        private void SetDeleteMode()
        {
            ActiveMode = "Delete";
            _renderer.SetActiveGizmoMesh(null);
            var state = new DeleteState(_glControlHost, _sceneManager, _camera, new RayCaster(_glControlHost, _camera), _commandHistory);
            _mouseController.SetState(state);
        }

        [RelayCommand]
        private void SetMoveMode()
        {
            ActiveMode = "Move";
            var state = new MoveState(_glControlHost, _sceneManager, _camera, new RayCaster(_glControlHost, _camera), _commandHistory, _renderer);
            // If a mesh is already selected, show arrows immediately — no need to click again.
            if (SelectedMesh != null)
                state.SetSelectedMesh(SelectedMesh);
            else
                _renderer.SetActiveGizmoMesh(null);
            _mouseController.SetState(state);
        }

        [RelayCommand]
        private void SetRotateMode()
        {
            ActiveMode = "Rotate";
            var state = new RotateState(_settingsManager, _sceneManager, _glControlHost, _camera, new RayCaster(_glControlHost, _camera), _commandHistory, _renderer);
            // If a mesh is already selected, show rings immediately — no need to click again.
            if (SelectedMesh != null)
                state.SetSelectedMesh(SelectedMesh);
            else
                _renderer.SetActiveGizmoMesh(null);
            _mouseController.SetState(state);
        }

        [RelayCommand]
        private void SetGimbalMode()
        {
            ActiveMode = "Gimbal";
            var state = new GimbalState(_glControlHost, _sceneManager, _camera, new RayCaster(_glControlHost, _camera), _commandHistory, _renderer);

            // If a mesh is already selected in the scene, show the gimbal rings immediately
            // without making the user click again.
            if (SelectedMesh != null)
            {
                state.SetSelectedMesh(SelectedMesh);
                _glControlHost.Invalidate();
            }

            _renderer.SetGizmoMode(GizmoMode.Full);
            _mouseController.SetState(state);
        }

        [RelayCommand]
        private void SetRulerMode()
        {
            ActiveMode = "Ruler";
            _renderer.SetActiveGizmoMesh(null);
            _renderer.SetGizmoMode(GizmoMode.None);
            var state = new RulerState(
                _glControlHost, _camera, new RayCaster(_glControlHost, _camera),
                _commandHistory, _rulerManager, _rulerRenderer);
            _mouseController.SetState(state);
            _glControlHost.Invalidate();
        }

        public RulerOverlayManager RulerOverlayManager => _rulerOverlayManager;

        #endregion

        /// <summary>
        /// Rebuilds the Meshes observable collection from the current scene.
        /// Called after undo/redo so the hierarchy stays in sync.
        /// </summary>
        private void RefreshMeshesCollection()
        {
            Meshes.Clear();
            foreach (var mesh in _sceneManager.GetMeshes())
                Meshes.Add(new MeshSummary(mesh));
        }

        public void ApplyMeshThreshold()
        {
            if (_latestImportedModel == null)
            {
                Debug.WriteLine("ApplyMeshThreshold called but no model is loaded.");
                return;
            }

            _sceneManager.RemoveSmallMeshes(_latestImportedModel, SmallMeshThreshold);
            Meshes.Clear();

            var importedMeshes = _sceneManager.GetMeshes();

            foreach (var mesh in importedMeshes)
            {
                Meshes.Add(new MeshSummary(mesh));
            }

        }
    }
}
